version: "1.0"
services:
  minecraft:
    restart: always
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "6G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/home/pi/mcserver:/data:rw"
    ports:
      - "25565:25565"
      - "19132:19132"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
