version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server:latest"
    restart: unless-stopped
    container_name: "mcserver"
    environment:
      MEMORYSIZE: "6G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/home/data:rw"
    ports:
      - "25565:25565"
      - "19132:19132"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
